version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-browsers
    working_directory: ~/repo

    environment:
      SELENIUM_HOST: hub.browserstack.com
      BS_AUTOMATE_PROJECT: "Run on circleCI"
      BS_AUTOMATE_BUILD: "build No. $CIRCLE_BUILD_NUM for circleCI"
      SELENIUM_PLATFORM: WINDOWS
      BS_AUTOMATE_OS_VERSION: 10
      SELENIUM_BROWSER: IE
      SELENIUM_VERSION: 11


    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem install bundler:2.0.1
            bundle update --bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
            unzip BrowserStackLocal-linux-x64.zip
            ./BrowserStackLocalenvi "xpVH9NPWHJQLZdR1mbgq":
            background: true

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format documentation \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
